#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Dec 29 14:11:24 2018

@author: account1
"""

#%%
    
input = '2 3 0 3 10 11 12 1 1 0 1 99 2 1 1 2'

listinput = input.split()

print(listinput)
    
#%%

i=0

initinput0 = '0 1 99'

while i < len(initinput0):
    print(initinput0[i])
    print('i is',i)
    i+=1
